package org.grupoandroid.ptibus.models;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import org.grupoandroid.ptibus.models.DiaSemana;
import org.grupoandroid.ptibus.models.Horario;
import org.grupoandroid.ptibus.models.Linha;
import org.grupoandroid.ptibus.models.Rota;
import org.grupoandroid.ptibus.models.horario_diaSemana;

import org.grupoandroid.ptibus.models.DiaSemanaDao;
import org.grupoandroid.ptibus.models.HorarioDao;
import org.grupoandroid.ptibus.models.LinhaDao;
import org.grupoandroid.ptibus.models.RotaDao;
import org.grupoandroid.ptibus.models.horario_diaSemanaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig diaSemanaDaoConfig;
    private final DaoConfig horarioDaoConfig;
    private final DaoConfig linhaDaoConfig;
    private final DaoConfig rotaDaoConfig;
    private final DaoConfig horario_diaSemanaDaoConfig;

    private final DiaSemanaDao diaSemanaDao;
    private final HorarioDao horarioDao;
    private final LinhaDao linhaDao;
    private final RotaDao rotaDao;
    private final horario_diaSemanaDao horario_diaSemanaDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        diaSemanaDaoConfig = daoConfigMap.get(DiaSemanaDao.class).clone();
        diaSemanaDaoConfig.initIdentityScope(type);

        horarioDaoConfig = daoConfigMap.get(HorarioDao.class).clone();
        horarioDaoConfig.initIdentityScope(type);

        linhaDaoConfig = daoConfigMap.get(LinhaDao.class).clone();
        linhaDaoConfig.initIdentityScope(type);

        rotaDaoConfig = daoConfigMap.get(RotaDao.class).clone();
        rotaDaoConfig.initIdentityScope(type);

        horario_diaSemanaDaoConfig = daoConfigMap.get(horario_diaSemanaDao.class).clone();
        horario_diaSemanaDaoConfig.initIdentityScope(type);

        diaSemanaDao = new DiaSemanaDao(diaSemanaDaoConfig, this);
        horarioDao = new HorarioDao(horarioDaoConfig, this);
        linhaDao = new LinhaDao(linhaDaoConfig, this);
        rotaDao = new RotaDao(rotaDaoConfig, this);
        horario_diaSemanaDao = new horario_diaSemanaDao(horario_diaSemanaDaoConfig, this);

        registerDao(DiaSemana.class, diaSemanaDao);
        registerDao(Horario.class, horarioDao);
        registerDao(Linha.class, linhaDao);
        registerDao(Rota.class, rotaDao);
        registerDao(horario_diaSemana.class, horario_diaSemanaDao);
    }
    
    public void clear() {
        diaSemanaDaoConfig.getIdentityScope().clear();
        horarioDaoConfig.getIdentityScope().clear();
        linhaDaoConfig.getIdentityScope().clear();
        rotaDaoConfig.getIdentityScope().clear();
        horario_diaSemanaDaoConfig.getIdentityScope().clear();
    }

    public DiaSemanaDao getDiaSemanaDao() {
        return diaSemanaDao;
    }

    public HorarioDao getHorarioDao() {
        return horarioDao;
    }

    public LinhaDao getLinhaDao() {
        return linhaDao;
    }

    public RotaDao getRotaDao() {
        return rotaDao;
    }

    public horario_diaSemanaDao getHorario_diaSemanaDao() {
        return horario_diaSemanaDao;
    }

}
