package org.grupoandroid.ptibus.models;

import java.util.List;
import org.grupoandroid.ptibus.models.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LINHA.
 */
public class Linha {

    private Long id;
    /** Not-null value. */
    private String origem;
    /** Not-null value. */
    private String destino;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient LinhaDao myDao;

    private List<Horario> horarios;

    public Linha() {
    }

    public Linha(Long id) {
        this.id = id;
    }

    public Linha(Long id, String origem, String destino) {
        this.id = id;
        this.origem = origem;
        this.destino = destino;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getLinhaDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getOrigem() {
        return origem;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOrigem(String origem) {
        this.origem = origem;
    }

    /** Not-null value. */
    public String getDestino() {
        return destino;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDestino(String destino) {
        this.destino = destino;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public synchronized List<Horario> getHorarios() {
        if (horarios == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            HorarioDao targetDao = daoSession.getHorarioDao();
            horarios = targetDao._queryLinha_Horarios(id);
        }
        return horarios;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetHorarios() {
        horarios = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
